import 'dart:convert';

import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:injectable/injectable.dart';
import 'package:my_portfolio/core/debug/debug_console_app_logger.dart';
import 'package:my_portfolio/core/extensions/list.dart';
import 'package:my_portfolio/core/extensions/string.dart';
import 'package:my_portfolio/presentation/features/json_to_dart/bloc/json_to_dart_state.dart';

/// Generates Dart model classes from a JSON object. All conversion logic lives
/// here (out of the widget); the screen only renders [JsonToDartState.output].
@injectable
class JsonToDartCubit extends Cubit<JsonToDartState>
    with DebugConsoleAppLogger {
  JsonToDartCubit() : super(const JsonToDartState());

  @override
  String get context => 'JsonToDartCubit';

  void clear() => emit(const JsonToDartState());

  /// Returns `null` on success, or an error message on invalid JSON.
  String? generate({required String jsonText, required String className}) {
    try {
      emit(const JsonToDartState());
      final parsed = jsonDecode(jsonText);
      Map<String, dynamic> parsedJson = {};
      if (parsed is List) {
        parsedJson = parsed.firstOrNull;
      } else if (parsed is Map<String, dynamic>) {
        parsedJson = parsed;
      }
      final (attributes, otherJson) = _attributesFromJson(parsedJson);
      var output = _convertedClass(attributes, className: className);
      output += _output(otherJson);
      emit(JsonToDartState(output: output));
      return null;
    } catch (error) {
      e('generate failed', error: error);
      return 'Something went wrong with the JSON, please check.';
    }
  }

  String _convertedClass(List<(String, String)> attributes,
      {String? className = ''}) {
    var name = (className == '' || className == null)
        ? 'Autogenerated'
        : className;
    name = name.capitalize();
    var converted = 'class $name{\n';
    converted += attributes.getRawAttributes;
    converted += '${attributes.getConstructor(name)}\n';
    converted += '\t\t$name.fromJson(Map<String, dynamic> json) {\n';
    converted += attributes.getFromJson;
    converted += '\t\t}\n';
    converted += '\t\tMap<String, dynamic> toJson() {\n';
    converted += attributes.getToJson;
    converted += '\t\t}\n';
    converted += '}\n\n';
    return converted;
  }

  (List<(String, String)>, List<(String, Map<String, dynamic>)>)
      _attributesFromJson(Map<String, dynamic> parsedJson) {
    final List<(String, String)> attributes = [];
    final List<(String, Map<String, dynamic>)> otherJson = [];
    for (final mapEntry in parsedJson.entries) {
      if (mapEntry.value is Map<String, dynamic>) {
        otherJson.add((mapEntry.key, mapEntry.value));
        attributes.add(((mapEntry.key.capitalize()), mapEntry.key));
      } else if (mapEntry.value is List) {
        final mapList = (mapEntry.value as List);
        try {
          final value =
              mapList.map((e) => Map<String, dynamic>.from(e)).toList();
          otherJson.add((mapEntry.key, value.first));
          attributes.add(('List<${mapEntry.key.capitalize()}>', mapEntry.key));
        } catch (_) {
          final typ = mapList.first.runtimeType;
          Type type = List<String>;
          if (typ == int) {
            type = List<int>;
          } else if (typ == double) {
            type = List<double>;
          } else if (typ == bool) {
            type = List<bool>;
          }
          attributes.add(('$type', mapEntry.key));
        }
      } else {
        attributes.add(('${mapEntry.value.runtimeType}', mapEntry.key));
      }
    }
    return (attributes, otherJson);
  }

  String _output(List<(String, Map<String, dynamic>)> extraJson) {
    var o = '';
    for (final element in extraJson) {
      final (attributes, otherJson) = _attributesFromJson(element.$2);
      o += _convertedClass(attributes, className: element.$1);
      o += _output(otherJson);
    }
    return o;
  }
}
